-- ============================================================================
-- EduCore — PostgreSQL 16 Schema (documentation form)
-- Target: 49 domain tables (business schema), plus 8 Laravel framework tables.
-- This is the DESCRIPTION-OF-RECORD for the designed schema. Implement via
-- Laravel migrations (see migration-strategy.md), not by running this file.
-- Conventions: see database-conventions.md. Relationships: see
-- relationships.md and skills/academic-domain/SKILL.md.
--
-- APPROVED EQUIVALENCES vs the Laravel migrations (verified 2026-09-25):
--   * PK: IDENTITY here vs bigserial (`$table->id()` with nextval) in the
--     migrations. Both auto-increment; both allow explicit id inserts.
--   * Timestamps: precision 6 + DEFAULT now() here vs precision 0 +
--     CURRENT_TIMESTAMP in the migrations. Equivalent for app writes
--     (application code never emits microseconds).
--   * `uq_gpa_records` (UNIQUE NULLS NOT DISTINCT) is a table CONSTRAINT here
--     but a unique INDEX in the migrations. Identical enforcement.
--   * users.email unique constraint is named `uq_users_email` here but
--     `users_email_unique` in the migrations (scaffold default).
--   * Numeric/smallint defaults differ only in catalog notation
--     (e.g. '100'::numeric vs 100); values identical.
--   The 49-domain/70-FK/57-CHECK/54+3-index structural surface matches exactly.
-- ============================================================================

START TRANSACTION;

-- ============================================================================
-- Module 1 — Identity & Access
-- ============================================================================

CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    slug        VARCHAR(100) NOT NULL,
    description TEXT,
    is_system   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_roles_name UNIQUE (name),
    CONSTRAINT uq_roles_slug UNIQUE (slug)
);

CREATE TABLE permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    slug        VARCHAR(100) NOT NULL,
    module      VARCHAR(100),
    description TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_permissions_name UNIQUE (name),
    CONSTRAINT uq_permissions_slug UNIQUE (slug)
);

CREATE INDEX idx_permissions_module ON permissions (module);

CREATE TABLE permission_role (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_permission_role UNIQUE (role_id, permission_id),
    CONSTRAINT fk_permission_role_role FOREIGN KEY (role_id)
        REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_permission_role_permission FOREIGN KEY (permission_id)
        REFERENCES permissions (id) ON DELETE CASCADE
);

CREATE INDEX idx_permission_role_permission ON permission_role (permission_id);

CREATE TABLE settings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key         VARCHAR(100) NOT NULL,
    value       TEXT,
    "group"            VARCHAR(50)  NOT NULL DEFAULT 'general',
    type        VARCHAR(20)  NOT NULL DEFAULT 'string',
    is_public   BOOLEAN      NOT NULL DEFAULT FALSE,
    description TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_settings_key UNIQUE (key)
);

CREATE INDEX idx_settings_group ON settings ("group");

-- users exists from the Laravel scaffold; extended shape below.
CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NOT NULL,
    email_verified_at TIMESTAMPTZ,
    password          VARCHAR(255) NOT NULL,
    remember_token    VARCHAR(100),
    role_id           BIGINT NOT NULL,
    phone             VARCHAR(50),
    avatar_key        VARCHAR(255),
    is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
    last_login_at     TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id)
        REFERENCES roles (id) ON DELETE RESTRICT
);

CREATE INDEX idx_users_role ON users (role_id);

-- ============================================================================
-- Module 2 — University Structure
-- ============================================================================

CREATE TABLE universities (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(255) NOT NULL,
    short_name  VARCHAR(100),
    address     TEXT,
    phone       VARCHAR(50),
    email       VARCHAR(150),
    logo_key    VARCHAR(255),
    website     VARCHAR(255),
    is_current  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_universities_code UNIQUE (code)
);

CREATE TABLE faculties (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id BIGINT NOT NULL,
    code          VARCHAR(50)  NOT NULL,
    name          VARCHAR(255) NOT NULL,
    dean_name     VARCHAR(255),
    description   TEXT,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ,
    CONSTRAINT uq_faculties_code UNIQUE (code),
    CONSTRAINT fk_faculties_university FOREIGN KEY (university_id)
        REFERENCES universities (id) ON DELETE RESTRICT
);

CREATE INDEX idx_faculties_university ON faculties (university_id);

CREATE TABLE departments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_id  BIGINT NOT NULL,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(255) NOT NULL,
    head_name   VARCHAR(255),
    description TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_departments_code UNIQUE (code),
    CONSTRAINT fk_departments_faculty FOREIGN KEY (faculty_id)
        REFERENCES faculties (id) ON DELETE RESTRICT
);

CREATE INDEX idx_departments_faculty ON departments (faculty_id);

CREATE TABLE programs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id    BIGINT NOT NULL,
    code             VARCHAR(50)    NOT NULL,
    name             VARCHAR(255)   NOT NULL,
    degree_level     VARCHAR(50)    NOT NULL,
    duration_years   SMALLINT,
    credits_required NUMERIC(5,1),
    is_active        BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uq_programs_code UNIQUE (code),
    CONSTRAINT fk_programs_department FOREIGN KEY (department_id)
        REFERENCES departments (id) ON DELETE RESTRICT
);

CREATE INDEX idx_programs_department ON programs (department_id);

-- ============================================================================
-- Module 3 — Academic Management
-- ============================================================================

CREATE TABLE academic_years (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50) NOT NULL,
    name        VARCHAR(100) NOT NULL,
    start_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'planned',
    is_current  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_academic_years_code UNIQUE (code),
    CONSTRAINT ck_academic_years_status
        CHECK (status IN ('planned', 'active', 'completed')),
    CONSTRAINT ck_academic_years_range CHECK (start_date < end_date)
);

CREATE TABLE semesters (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year_id BIGINT NOT NULL,
    name             VARCHAR(50) NOT NULL,
    code             VARCHAR(20) NOT NULL,
    sequence         SMALLINT NOT NULL,
    start_date       DATE,
    end_date         DATE,
    enrollment_start DATE,
    enrollment_end   DATE,
    exam_start       DATE,
    exam_end         DATE,
    status           VARCHAR(20) NOT NULL DEFAULT 'planned',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_semesters_year_sequence UNIQUE (academic_year_id, sequence),
    CONSTRAINT ck_semesters_status
        CHECK (status IN ('planned', 'open', 'closed', 'completed')),
    CONSTRAINT ck_semesters_range CHECK (start_date IS NULL OR end_date IS NULL OR start_date <= end_date),
    CONSTRAINT fk_semesters_year FOREIGN KEY (academic_year_id)
        REFERENCES academic_years (id) ON DELETE RESTRICT
);

CREATE INDEX idx_semesters_academic_year ON semesters (academic_year_id);

CREATE TABLE courses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT       NOT NULL,
    code          VARCHAR(20)  NOT NULL,
    name          VARCHAR(255) NOT NULL,
    credits       NUMERIC(4,2) NOT NULL,
    lecture_hours SMALLINT,
    lab_hours     SMALLINT,
    description   TEXT,
    course_level  VARCHAR(20),
    status        VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_courses_code UNIQUE (code),
    CONSTRAINT ck_courses_credits CHECK (credits > 0),
    CONSTRAINT ck_courses_status CHECK (status IN ('draft', 'active', 'archived')),
    CONSTRAINT fk_courses_department FOREIGN KEY (department_id)
        REFERENCES departments (id) ON DELETE RESTRICT
);

CREATE INDEX idx_courses_department ON courses (department_id);
CREATE INDEX idx_courses_status ON courses (status);

CREATE TABLE course_programs (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id          BIGINT NOT NULL,
    program_id         BIGINT NOT NULL,
    is_required        BOOLEAN NOT NULL DEFAULT FALSE,
    suggested_semester SMALLINT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_course_programs UNIQUE (course_id, program_id),
    CONSTRAINT fk_course_programs_course FOREIGN KEY (course_id)
        REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_programs_program FOREIGN KEY (program_id)
        REFERENCES programs (id) ON DELETE CASCADE
);

CREATE INDEX idx_course_programs_program ON course_programs (program_id);

CREATE TABLE course_prerequisites (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id               BIGINT NOT NULL,
    prerequisite_course_id  BIGINT NOT NULL,
    is_strict               BOOLEAN NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_course_prerequisites UNIQUE (course_id, prerequisite_course_id),
    CONSTRAINT ck_course_prerequisites_not_self CHECK (course_id <> prerequisite_course_id),
    CONSTRAINT fk_course_prerequisites_course FOREIGN KEY (course_id)
        REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_prerequisites_prereq FOREIGN KEY (prerequisite_course_id)
        REFERENCES courses (id) ON DELETE RESTRICT
);

CREATE INDEX idx_course_prerequisites_prereq ON course_prerequisites (prerequisite_course_id);

CREATE TABLE course_offerings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id       BIGINT NOT NULL,
    semester_id     BIGINT NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'draft',
    max_enrollments INTEGER,
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_course_offerings UNIQUE (course_id, semester_id),
    CONSTRAINT ck_course_offerings_status
        CHECK (status IN ('draft', 'published', 'open', 'closed')),
    CONSTRAINT fk_course_offerings_course FOREIGN KEY (course_id)
        REFERENCES courses (id) ON DELETE RESTRICT,
    CONSTRAINT fk_course_offerings_semester FOREIGN KEY (semester_id)
        REFERENCES semesters (id) ON DELETE RESTRICT
);

CREATE INDEX idx_course_offerings_semester ON course_offerings (semester_id);

CREATE TABLE sections (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_offering_id BIGINT NOT NULL,
    code               VARCHAR(20) NOT NULL,
    name               VARCHAR(100),
    capacity           SMALLINT NOT NULL DEFAULT 30,
    status             VARCHAR(20) NOT NULL DEFAULT 'draft',
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_sections_offering_code UNIQUE (course_offering_id, code),
    CONSTRAINT ck_sections_capacity CHECK (capacity >= 0),
    CONSTRAINT ck_sections_status
        CHECK (status IN ('draft', 'open', 'active', 'closed', 'archived')),
    CONSTRAINT fk_sections_offering FOREIGN KEY (course_offering_id)
        REFERENCES course_offerings (id) ON DELETE RESTRICT
);

CREATE INDEX idx_sections_offering ON sections (course_offering_id);

CREATE TABLE rooms (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    building    VARCHAR(100),
    floor       VARCHAR(20),
    capacity    SMALLINT NOT NULL,
    room_type   VARCHAR(20) NOT NULL DEFAULT 'lecture',
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_rooms_code UNIQUE (code),
    CONSTRAINT ck_rooms_capacity CHECK (capacity > 0),
    CONSTRAINT ck_rooms_type CHECK (room_type IN ('lecture', 'lab', 'seminar', 'other'))
);

CREATE TABLE schedule_entries (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id   BIGINT NOT NULL,
    room_id      BIGINT NOT NULL,
    day_of_week  SMALLINT NOT NULL,
    start_time   TIME NOT NULL,
    end_time     TIME NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_schedule_section_slot UNIQUE (section_id, day_of_week, start_time),
    CONSTRAINT uq_schedule_room_slot UNIQUE (room_id, day_of_week, start_time, end_time),
    CONSTRAINT ck_schedule_dow CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT ck_schedule_times CHECK (start_time < end_time),
    CONSTRAINT fk_schedule_section FOREIGN KEY (section_id)
        REFERENCES sections (id) ON DELETE RESTRICT,
    CONSTRAINT fk_schedule_room FOREIGN KEY (room_id)
        REFERENCES rooms (id) ON DELETE RESTRICT
);

CREATE INDEX idx_schedule_room ON schedule_entries (room_id);

CREATE TABLE lecturers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    staff_number    VARCHAR(50) NOT NULL,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    title           VARCHAR(50),
    department_id   BIGINT NOT NULL,
    position        VARCHAR(100),
    specialization  VARCHAR(255),
    employment_type VARCHAR(20) NOT NULL DEFAULT 'full_time',
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_lecturers_user UNIQUE (user_id),
    CONSTRAINT uq_lecturers_staff_number UNIQUE (staff_number),
    CONSTRAINT ck_lecturers_employment CHECK (employment_type IN
        ('full_time', 'part_time', 'contract', 'visiting')),
    CONSTRAINT fk_lecturers_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_lecturers_department FOREIGN KEY (department_id)
        REFERENCES departments (id) ON DELETE RESTRICT
);

CREATE INDEX idx_lecturers_department ON lecturers (department_id);

CREATE TABLE section_lecturers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id  BIGINT NOT NULL,
    lecturer_id BIGINT NOT NULL,
    role        VARCHAR(20) NOT NULL DEFAULT 'primary',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_section_lecturers UNIQUE (section_id, lecturer_id),
    CONSTRAINT ck_section_lecturers_role CHECK (role IN ('primary', 'assistant', 'tutor')),
    CONSTRAINT fk_section_lecturers_section FOREIGN KEY (section_id)
        REFERENCES sections (id) ON DELETE CASCADE,
    CONSTRAINT fk_section_lecturers_lecturer FOREIGN KEY (lecturer_id)
        REFERENCES lecturers (id) ON DELETE RESTRICT
);

CREATE INDEX idx_section_lecturers_lecturer ON section_lecturers (lecturer_id);

-- Exactly one primary lecturer per section.
CREATE UNIQUE INDEX uq_section_lecturers_primary
    ON section_lecturers (section_id) WHERE role = 'primary';

-- ============================================================================
-- Module 4 — People
-- ============================================================================

CREATE TABLE students (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT NOT NULL,
    student_number         VARCHAR(50) NOT NULL,
    first_name             VARCHAR(100) NOT NULL,
    last_name              VARCHAR(100) NOT NULL,
    gender                 VARCHAR(20),
    date_of_birth          DATE,
    address                TEXT,
    emergency_contact_name VARCHAR(150),
    emergency_contact_phone VARCHAR(50),
    national_id            VARCHAR(50),
    enrollment_date        DATE,
    status                 VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_students_user UNIQUE (user_id),
    CONSTRAINT uq_students_student_number UNIQUE (student_number),
    CONSTRAINT uq_students_national_id UNIQUE (national_id),
    CONSTRAINT ck_students_gender CHECK (gender IN ('male', 'female', 'other')),
    CONSTRAINT ck_students_status CHECK (status IN
        ('active', 'inactive', 'suspended', 'graduated', 'withdrawn')),
    CONSTRAINT fk_students_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX idx_students_status ON students (status);

CREATE TABLE student_programs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id  BIGINT NOT NULL,
    program_id  BIGINT NOT NULL,
    started_on  DATE NOT NULL,
    ended_on    DATE,
    status      VARCHAR(20) NOT NULL DEFAULT 'active',
    notes       TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_student_programs UNIQUE (student_id, program_id, started_on),
    CONSTRAINT ck_student_programs_status CHECK (status IN
        ('active', 'completed', 'withdrawn', 'transferred')),
    CONSTRAINT ck_student_programs_dates CHECK (ended_on IS NULL OR ended_on >= started_on),
    CONSTRAINT fk_student_programs_student FOREIGN KEY (student_id)
        REFERENCES students (id) ON DELETE RESTRICT,
    CONSTRAINT fk_student_programs_program FOREIGN KEY (program_id)
        REFERENCES programs (id) ON DELETE RESTRICT
);

CREATE INDEX idx_student_programs_program ON student_programs (program_id);

-- Exactly one active program per student.
CREATE UNIQUE INDEX uq_student_programs_active
    ON student_programs (student_id) WHERE status = 'active';

-- ============================================================================
-- Module 5 — Enrollment
-- ============================================================================

CREATE TABLE enrollments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id       BIGINT NOT NULL,
    section_id       BIGINT NOT NULL,
    academic_year_id BIGINT NOT NULL,
    semester_id      BIGINT NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'pending',
    enrolled_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    dropped_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at       TIMESTAMPTZ,
    CONSTRAINT uq_enrollments_student_section UNIQUE (student_id, section_id),
    CONSTRAINT ck_enrollments_status CHECK (status IN
        ('pending', 'confirmed', 'completed', 'dropped', 'withdrawn')),
    CONSTRAINT fk_enrollments_student FOREIGN KEY (student_id)
        REFERENCES students (id) ON DELETE RESTRICT,
    CONSTRAINT fk_enrollments_section FOREIGN KEY (section_id)
        REFERENCES sections (id) ON DELETE RESTRICT,
    CONSTRAINT fk_enrollments_year FOREIGN KEY (academic_year_id)
        REFERENCES academic_years (id) ON DELETE RESTRICT,
    CONSTRAINT fk_enrollments_semester FOREIGN KEY (semester_id)
        REFERENCES semesters (id) ON DELETE RESTRICT
);

CREATE INDEX idx_enrollments_year_semester ON enrollments (academic_year_id, semester_id);
CREATE INDEX idx_enrollments_section_status ON enrollments (section_id, status);
CREATE INDEX idx_enrollments_student_year ON enrollments (student_id, academic_year_id);

-- ============================================================================
-- Module 6 — Attendance
-- ============================================================================

CREATE TABLE attendance_sessions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id   BIGINT NOT NULL,
    session_date DATE NOT NULL,
    start_time   TIME,
    end_time     TIME,
    topic        VARCHAR(255),
    status       VARCHAR(20) NOT NULL DEFAULT 'held',
    recorded_by  BIGINT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_attendance_sessions_section_date UNIQUE (section_id, session_date),
    CONSTRAINT ck_attendance_sessions_status CHECK (status IN ('scheduled', 'held', 'cancelled')),
    CONSTRAINT fk_attendance_sessions_section FOREIGN KEY (section_id)
        REFERENCES sections (id) ON DELETE RESTRICT,
    CONSTRAINT fk_attendance_sessions_recorder FOREIGN KEY (recorded_by)
        REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_attendance_sessions_recorder ON attendance_sessions (recorded_by);

CREATE TABLE attendance_records (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_session_id  BIGINT NOT NULL,
    enrollment_id          BIGINT NOT NULL,
    status                 VARCHAR(20) NOT NULL,
    remarks                TEXT,
    marked_by              BIGINT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_attendance_records_session_enrollment UNIQUE (attendance_session_id, enrollment_id),
    CONSTRAINT ck_attendance_records_status CHECK (status IN
        ('present', 'absent', 'late', 'excused')),
    CONSTRAINT fk_attendance_records_session FOREIGN KEY (attendance_session_id)
        REFERENCES attendance_sessions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_attendance_records_enrollment FOREIGN KEY (enrollment_id)
        REFERENCES enrollments (id) ON DELETE RESTRICT,
    CONSTRAINT fk_attendance_records_marker FOREIGN KEY (marked_by)
        REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_attendance_records_enrollment ON attendance_records (enrollment_id);

-- ============================================================================
-- Module 7 — Assessment
-- ============================================================================

CREATE TABLE assignments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id      BIGINT NOT NULL,
    title           VARCHAR(255) NOT NULL,
    description     TEXT,
    instructions    TEXT,
    max_score       NUMERIC(6,2) NOT NULL DEFAULT 100,
    due_at          TIMESTAMPTZ NOT NULL,
    assignment_type VARCHAR(20) NOT NULL DEFAULT 'homework',
    weight_override NUMERIC(5,2),
    is_published    BOOLEAN NOT NULL DEFAULT FALSE,
    published_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_assignments_max_score CHECK (max_score > 0),
    CONSTRAINT ck_assignments_type CHECK (assignment_type IN
        ('homework', 'quiz', 'project', 'presentation', 'other')),
    CONSTRAINT fk_assignments_section FOREIGN KEY (section_id)
        REFERENCES sections (id) ON DELETE RESTRICT
);

CREATE INDEX idx_assignments_section_due ON assignments (section_id, due_at);

CREATE TABLE assignment_submissions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT NOT NULL,
    enrollment_id BIGINT NOT NULL,
    submitted_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    status        VARCHAR(20) NOT NULL DEFAULT 'submitted',
    score         NUMERIC(6,2),
    feedback      TEXT,
    graded_by     BIGINT,
    graded_at     TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_assignment_submissions UNIQUE (assignment_id, enrollment_id),
    CONSTRAINT ck_assignment_submissions_status CHECK (status IN
        ('submitted', 'late', 'graded', 'returned')),
    CONSTRAINT ck_assignment_submissions_score CHECK (score >= 0),
    CONSTRAINT fk_assignment_submissions_assignment FOREIGN KEY (assignment_id)
        REFERENCES assignments (id) ON DELETE RESTRICT,
    CONSTRAINT fk_assignment_submissions_enrollment FOREIGN KEY (enrollment_id)
        REFERENCES enrollments (id) ON DELETE RESTRICT,
    CONSTRAINT fk_assignment_submissions_grader FOREIGN KEY (graded_by)
        REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_assignment_submissions_enrollment ON assignment_submissions (enrollment_id);

-- ============================================================================
-- Module 8 — Examination & Grading
-- ============================================================================

CREATE TABLE exams (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id     BIGINT NOT NULL,
    exam_type      VARCHAR(20) NOT NULL,
    title          VARCHAR(255) NOT NULL,
    weight         NUMERIC(5,2) NOT NULL DEFAULT 0,
    max_score      NUMERIC(6,2) NOT NULL DEFAULT 100,
    scheduled_date DATE,
    start_time     TIME,
    end_time       TIME,
    location       VARCHAR(255),
    is_published   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_exams_type CHECK (exam_type IN
        ('midterm', 'final', 'quiz', 'practical', 'other')),
    CONSTRAINT ck_exams_weight CHECK (weight >= 0),
    CONSTRAINT ck_exams_max_score CHECK (max_score > 0),
    CONSTRAINT fk_exams_section FOREIGN KEY (section_id)
        REFERENCES sections (id) ON DELETE RESTRICT
);

CREATE INDEX idx_exams_section_type ON exams (section_id, exam_type);

CREATE TABLE exam_results (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id       BIGINT NOT NULL,
    enrollment_id BIGINT NOT NULL,
    score         NUMERIC(6,2),
    remarks       TEXT,
    recorded_by   BIGINT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_exam_results UNIQUE (exam_id, enrollment_id),
    CONSTRAINT ck_exam_results_score CHECK (score >= 0),
    CONSTRAINT fk_exam_results_exam FOREIGN KEY (exam_id)
        REFERENCES exams (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exam_results_enrollment FOREIGN KEY (enrollment_id)
        REFERENCES enrollments (id) ON DELETE RESTRICT,
    CONSTRAINT fk_exam_results_recorder FOREIGN KEY (recorded_by)
        REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_exam_results_enrollment ON exam_results (enrollment_id);

CREATE TABLE grading_scales (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100) NOT NULL,
    grade          VARCHAR(5) NOT NULL,
    min_percentage NUMERIC(5,2) NOT NULL,
    max_percentage NUMERIC(5,2) NOT NULL,
    grade_point    NUMERIC(3,2) NOT NULL,
    is_pass        BOOLEAN NOT NULL DEFAULT TRUE,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_grading_scales_name_grade UNIQUE (name, grade),
    CONSTRAINT ck_grading_scales_range CHECK (min_percentage <= max_percentage)
);

CREATE TABLE course_grading_configs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id         BIGINT NOT NULL,
    attendance_weight NUMERIC(5,2) NOT NULL DEFAULT 10,
    assignment_weight NUMERIC(5,2) NOT NULL DEFAULT 25,
    midterm_weight    NUMERIC(5,2) NOT NULL DEFAULT 20,
    final_weight      NUMERIC(5,2) NOT NULL DEFAULT 40,
    practical_weight  NUMERIC(5,2) NOT NULL DEFAULT 5,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_course_grading_configs UNIQUE (course_id),
    CONSTRAINT ck_course_grading_configs_nonneg CHECK (
        attendance_weight >= 0 AND assignment_weight >= 0 AND
        midterm_weight >= 0 AND final_weight >= 0 AND practical_weight >= 0),
    CONSTRAINT ck_course_grading_configs_sum CHECK (
        attendance_weight + assignment_weight + midterm_weight +
        final_weight + practical_weight = 100),
    CONSTRAINT fk_course_grading_configs_course FOREIGN KEY (course_id)
        REFERENCES courses (id) ON DELETE RESTRICT
);

CREATE TABLE grades (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id BIGINT NOT NULL,
    letter_grade  VARCHAR(5),
    grade_point   NUMERIC(3,2),
    total_score   NUMERIC(6,2),
    status        VARCHAR(20) NOT NULL DEFAULT 'draft',
    graded_by     BIGINT,
    submitted_at  TIMESTAMPTZ,
    approved_at   TIMESTAMPTZ,
    remarks       TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ,
    CONSTRAINT uq_grades_enrollment UNIQUE (enrollment_id),
    CONSTRAINT ck_grades_status CHECK (status IN
        ('draft', 'submitted', 'approved', 'finalized')),
    CONSTRAINT fk_grades_enrollment FOREIGN KEY (enrollment_id)
        REFERENCES enrollments (id) ON DELETE RESTRICT,
    CONSTRAINT fk_grades_graded_by FOREIGN KEY (graded_by)
        REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_grades_status_approved ON grades (status, approved_at);

CREATE TABLE gpa_records (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id       BIGINT NOT NULL,
    academic_year_id BIGINT NOT NULL,
    semester_id      BIGINT,
    gpa_value        NUMERIC(4,3) NOT NULL,
    attempted_credits NUMERIC(6,2),
    earned_credits   NUMERIC(6,2),
    grade_points     NUMERIC(6,2),
    cumulative       BOOLEAN NOT NULL DEFAULT FALSE,
    computed_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_gpa_records UNIQUE NULLS NOT DISTINCT
        (student_id, academic_year_id, semester_id),
    CONSTRAINT ck_gpa_records_value CHECK (gpa_value >= 0),
    CONSTRAINT fk_gpa_records_student FOREIGN KEY (student_id)
        REFERENCES students (id) ON DELETE RESTRICT,
    CONSTRAINT fk_gpa_records_year FOREIGN KEY (academic_year_id)
        REFERENCES academic_years (id) ON DELETE RESTRICT,
    CONSTRAINT fk_gpa_records_semester FOREIGN KEY (semester_id)
        REFERENCES semesters (id) ON DELETE RESTRICT
);

CREATE INDEX idx_gpa_records_student ON gpa_records (student_id);

-- ============================================================================
-- Module 9 — Documents & File Storage
-- ============================================================================

CREATE TABLE document_types (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(50)  NOT NULL,
    name          VARCHAR(150) NOT NULL,
    description   TEXT,
    requires_fee  BOOLEAN NOT NULL DEFAULT FALSE,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order    SMALLINT NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_document_types_code UNIQUE (code)
);

CREATE TABLE document_requests (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id       BIGINT NOT NULL,
    document_type_id BIGINT NOT NULL,
    academic_year_id BIGINT,
    semester_id      BIGINT,
    reason           TEXT,
    status           VARCHAR(20) NOT NULL DEFAULT 'pending',
    submitted_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_by     BIGINT,
    processed_at     TIMESTAMPTZ,
    rejection_reason TEXT,
    notes            TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_document_requests_status CHECK (status IN
        ('pending', 'approved', 'rejected', 'generated')),
    CONSTRAINT fk_document_requests_student FOREIGN KEY (student_id)
        REFERENCES students (id) ON DELETE RESTRICT,
    CONSTRAINT fk_document_requests_type FOREIGN KEY (document_type_id)
        REFERENCES document_types (id) ON DELETE RESTRICT,
    CONSTRAINT fk_document_requests_year FOREIGN KEY (academic_year_id)
        REFERENCES academic_years (id) ON DELETE RESTRICT,
    CONSTRAINT fk_document_requests_semester FOREIGN KEY (semester_id)
        REFERENCES semesters (id) ON DELETE RESTRICT,
    CONSTRAINT fk_document_requests_processor FOREIGN KEY (processed_by)
        REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_document_requests_status ON document_requests (status, submitted_at);
CREATE INDEX idx_document_requests_student ON document_requests (student_id);

CREATE TABLE documents (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_request_id BIGINT NOT NULL,
    file_key            VARCHAR(255) NOT NULL,
    file_name           VARCHAR(255) NOT NULL,
    mime_type           VARCHAR(100),
    file_size           BIGINT,
    checksum            VARCHAR(64),
    verification_token  VARCHAR(64) NOT NULL,
    generated_by        BIGINT,
    generated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    status              VARCHAR(20) NOT NULL DEFAULT 'valid',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT uq_documents_request UNIQUE (document_request_id),
    CONSTRAINT uq_documents_verification_token UNIQUE (verification_token),
    CONSTRAINT ck_documents_status CHECK (status IN ('valid', 'revoked', 'expired')),
    CONSTRAINT fk_documents_request FOREIGN KEY (document_request_id)
        REFERENCES document_requests (id) ON DELETE RESTRICT,
    CONSTRAINT fk_documents_generator FOREIGN KEY (generated_by)
        REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE document_verifications (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id        BIGINT NOT NULL,
    verification_token VARCHAR(64) NOT NULL,
    result             VARCHAR(20) NOT NULL,
    verified_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    ip_address         VARCHAR(45),
    user_agent         TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_document_verifications_result CHECK (result IN
        ('valid', 'invalid', 'revoked', 'expired')),
    CONSTRAINT fk_document_verifications_document FOREIGN KEY (document_id)
        REFERENCES documents (id) ON DELETE RESTRICT
);

CREATE INDEX idx_document_verifications_document ON document_verifications (document_id);
CREATE INDEX idx_document_verifications_token ON document_verifications (verification_token);
CREATE INDEX idx_document_verifications_verified ON document_verifications (verified_at);

CREATE TABLE files (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fileable_type VARCHAR(255),
    fileable_id   BIGINT,
    uploader_id   BIGINT,
    file_name     VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    storage_key   VARCHAR(255) NOT NULL,
    bucket        VARCHAR(100) NOT NULL DEFAULT 'educore',
    mime_type     VARCHAR(100),
    size          BIGINT NOT NULL,
    visibility    VARCHAR(20) NOT NULL DEFAULT 'private',
    checksum      VARCHAR(64),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_files_visibility CHECK (visibility IN ('private', 'public')),
    CONSTRAINT fk_files_uploader FOREIGN KEY (uploader_id)
        REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_files_fileable ON files (fileable_type, fileable_id);
CREATE INDEX idx_files_uploader ON files (uploader_id);

-- ============================================================================
-- Module 10 — Finance
-- ============================================================================

CREATE TABLE invoices (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id    BIGINT NOT NULL,
    invoice_number VARCHAR(50) NOT NULL,
    title         VARCHAR(255) NOT NULL,
    description   TEXT,
    currency      VARCHAR(10) NOT NULL DEFAULT 'USD',
    subtotal      NUMERIC(12,2) NOT NULL DEFAULT 0,
    discount      NUMERIC(12,2) NOT NULL DEFAULT 0,
    total         NUMERIC(12,2) NOT NULL,
    amount_paid   NUMERIC(12,2) NOT NULL DEFAULT 0,
    status        VARCHAR(20) NOT NULL DEFAULT 'pending',
    issued_date   DATE NOT NULL DEFAULT CURRENT_DATE,
    due_date      DATE NOT NULL,
    notes         TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ,
    CONSTRAINT uq_invoices_number UNIQUE (invoice_number),
    CONSTRAINT ck_invoices_status CHECK (status IN
        ('pending', 'partial', 'paid', 'overdue', 'cancelled')),
    CONSTRAINT ck_invoices_total CHECK (total >= 0),
    CONSTRAINT ck_invoices_paid CHECK (amount_paid >= 0 AND amount_paid <= total),
    CONSTRAINT fk_invoices_student FOREIGN KEY (student_id)
        REFERENCES students (id) ON DELETE RESTRICT
);

CREATE INDEX idx_invoices_student_status ON invoices (student_id, status);
CREATE INDEX idx_invoices_due_date ON invoices (due_date);

CREATE TABLE invoice_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT NOT NULL,
    description VARCHAR(255) NOT NULL,
    quantity    NUMERIC(8,2) NOT NULL DEFAULT 1,
    unit_price  NUMERIC(12,2) NOT NULL,
    amount      NUMERIC(12,2) NOT NULL,
    fee_category VARCHAR(50),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_invoice_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_invoice_items_unit_price CHECK (unit_price >= 0),
    CONSTRAINT ck_invoice_items_amount CHECK (amount = quantity * unit_price),
    CONSTRAINT fk_invoice_items_invoice FOREIGN KEY (invoice_id)
        REFERENCES invoices (id) ON DELETE CASCADE
);

CREATE INDEX idx_invoice_items_invoice ON invoice_items (invoice_id);

CREATE TABLE payments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id   BIGINT NOT NULL,
    amount       NUMERIC(12,2) NOT NULL,
    paid_on      DATE NOT NULL,
    method       VARCHAR(20) NOT NULL,
    reference    VARCHAR(100),
    received_by  BIGINT,
    notes        TEXT,
    is_reversal  BOOLEAN NOT NULL DEFAULT FALSE,
    reversal_of  BIGINT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_payments_amount CHECK (amount > 0),
    CONSTRAINT ck_payments_method CHECK (method IN
        ('cash', 'bank_transfer', 'cheque', 'other')),
    CONSTRAINT fk_payments_invoice FOREIGN KEY (invoice_id)
        REFERENCES invoices (id) ON DELETE RESTRICT,
    CONSTRAINT fk_payments_received_by FOREIGN KEY (received_by)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_payments_reversal_of FOREIGN KEY (reversal_of)
        REFERENCES payments (id) ON DELETE SET NULL
);

CREATE INDEX idx_payments_invoice ON payments (invoice_id);
CREATE INDEX idx_payments_paid_on ON payments (paid_on);

-- ============================================================================
-- Module 11 — Communication
-- ============================================================================

CREATE TABLE announcements (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id        BIGINT NOT NULL,
    title            VARCHAR(255) NOT NULL,
    body             TEXT NOT NULL,
    announcement_type VARCHAR(30),
    audience_type    VARCHAR(30) NOT NULL DEFAULT 'all',
    audience_id      BIGINT,
    publish_state    VARCHAR(20) NOT NULL DEFAULT 'draft',
    published_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_announcements_type CHECK (announcement_type IS NULL OR
        announcement_type IN ('general', 'academic', 'administrative', 'event')),
    CONSTRAINT ck_announcements_audience CHECK (audience_type IN
        ('all', 'students', 'lecturers', 'staff', 'faculty', 'department',
         'program', 'section', 'course')),
    CONSTRAINT ck_announcements_publish CHECK (publish_state IN
        ('draft', 'published', 'archived')),
    CONSTRAINT fk_announcements_author FOREIGN KEY (author_id)
        REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX idx_announcements_audience ON announcements (audience_type, audience_id);
CREATE INDEX idx_announcements_published ON announcements (publish_state, published_at);

CREATE TABLE notifications (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notifiable_type  VARCHAR(255) NOT NULL,
    notifiable_id    BIGINT NOT NULL,
    type             VARCHAR(255) NOT NULL,
    data             JSONB,
    read_at          TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_notifications_notifiable ON notifications (notifiable_type, notifiable_id);
CREATE INDEX idx_notifications_read ON notifications (read_at);

CREATE TABLE notification_preferences (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL,
    notify_by_email    BOOLEAN NOT NULL DEFAULT TRUE,
    notify_by_telegram BOOLEAN NOT NULL DEFAULT TRUE,
    telegram_chat_id   VARCHAR(100),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_notification_preferences_user UNIQUE (user_id),
    CONSTRAINT fk_notification_preferences_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE RESTRICT
);

-- ============================================================================
-- Module 12 — Internship
-- ============================================================================

CREATE TABLE internship_companies (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    industry      VARCHAR(100),
    contact_name  VARCHAR(150),
    contact_email VARCHAR(150),
    contact_phone VARCHAR(50),
    address       TEXT,
    website       VARCHAR(255),
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_internship_companies_name UNIQUE (name)
);

CREATE TABLE internships (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id       BIGINT NOT NULL,
    company_id       BIGINT NOT NULL,
    position_title   VARCHAR(255) NOT NULL,
    description      TEXT,
    start_date       DATE,
    end_date         DATE,
    supervisor_name  VARCHAR(150),
    supervisor_email VARCHAR(150),
    supervisor_phone VARCHAR(50),
    status           VARCHAR(30) NOT NULL DEFAULT 'draft',
    submitted_at     TIMESTAMPTZ,
    reviewed_by      BIGINT,
    reviewed_at      TIMESTAMPTZ,
    notes            TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_internships_status CHECK (status IN
        ('draft', 'submitted', 'under_review', 'approved', 'rejected',
         'in_progress', 'completed', 'cancelled')),
    CONSTRAINT ck_internships_dates CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT fk_internships_student FOREIGN KEY (student_id)
        REFERENCES students (id) ON DELETE RESTRICT,
    CONSTRAINT fk_internships_company FOREIGN KEY (company_id)
        REFERENCES internship_companies (id) ON DELETE RESTRICT,
    CONSTRAINT fk_internships_reviewer FOREIGN KEY (reviewed_by)
        REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_internships_student_status ON internships (student_id, status);
CREATE INDEX idx_internships_company ON internships (company_id);

-- One open application per student.
CREATE UNIQUE INDEX uq_internships_active
    ON internships (student_id) WHERE status IN ('submitted', 'under_review', 'approved', 'in_progress');

CREATE TABLE internship_reports (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    internship_id    BIGINT NOT NULL,
    report_type      VARCHAR(30) NOT NULL DEFAULT 'progress',
    title            VARCHAR(255) NOT NULL,
    summary          TEXT,
    submitted_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    status           VARCHAR(20) NOT NULL DEFAULT 'submitted',
    reviewer_comment TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_internship_reports_type CHECK (report_type IN
        ('initial', 'progress', 'final')),
    CONSTRAINT ck_internship_reports_status CHECK (status IN
        ('draft', 'submitted', 'reviewed')),
    CONSTRAINT fk_internship_reports_internship FOREIGN KEY (internship_id)
        REFERENCES internships (id) ON DELETE RESTRICT
);

CREATE INDEX idx_internship_reports_internship ON internship_reports (internship_id);

CREATE TABLE internship_evaluations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    internship_id  BIGINT NOT NULL,
    evaluator_type VARCHAR(30) NOT NULL,
    evaluator_name VARCHAR(150),
    score          NUMERIC(5,2),
    rating         VARCHAR(20),
    comments       TEXT,
    evaluated_at   TIMESTAMPTZ,
    submitted_by   BIGINT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_internship_evaluations_type CHECK (evaluator_type IN
        ('supervisor', 'faculty')),
    CONSTRAINT ck_internship_evaluations_score CHECK (score BETWEEN 0 AND 100),
    CONSTRAINT fk_internship_evaluations_internship FOREIGN KEY (internship_id)
        REFERENCES internships (id) ON DELETE RESTRICT,
    CONSTRAINT fk_internship_evaluations_submitter FOREIGN KEY (submitted_by)
        REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_internship_evaluations_internship ON internship_evaluations (internship_id);

-- ============================================================================
-- Module 14 — Audit & Security
-- ============================================================================

CREATE TABLE audit_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id       BIGINT,
    action         VARCHAR(100) NOT NULL,
    description    TEXT,
    auditable_type VARCHAR(255),
    auditable_id   BIGINT,
    before_values  JSONB,
    after_values   JSONB,
    ip_address     VARCHAR(45),
    user_agent     TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_audit_logs_actor FOREIGN KEY (actor_id)
        REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_audit_logs_target ON audit_logs (auditable_type, auditable_id);
CREATE INDEX idx_audit_logs_actor ON audit_logs (actor_id);
CREATE INDEX idx_audit_logs_action ON audit_logs (action);
CREATE INDEX idx_audit_logs_created ON audit_logs (created_at);

-- ============================================================================
-- Sanity checks
-- Tables: 49 domain tables in this file.
-- ============================================================================

COMMIT;